---
- name: home-server setup
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secret.yml

  handlers:
    - name: restart dnsmasq
      runit:
        name: dnsmasq
        state: restarted

    - name: restart haproxy
      runit:
        name: haproxy
        state: restarted

    - name: restart network
      command: /etc/rc.local

    - name: restart radvd
      runit:
        name: radvd
        state: restarted

    - name: restart sshd
      runit:
        name: sshd
        state: restarted

  tasks:
    - include_tasks: tasks/xbps.yml

    - name: Install packages
      xbps:
        name:
          - bat
          - bind-utils
          - chrony
          - cronie
          - curl
          - lsof
          - jq
          - most
          - psmisc
          - python3
          - python3-pip
          - python3-setuptools
          - ripgrep
          - socklog
          - socklog-void
          - ssh-audit
          - vim-huge
          - zsh

    - name: Enable socklog
      runit:
        name: socklog-unix
        enabled: yes

    - name: Enable chrony
      runit:
        name: chronyd
        enabled: yes

    - name: Enable cronie
      runit:
        name: cronie
        enabled: yes

    - name: Set user shell
      user:
        name: "{{ item }}"
        shell: /bin/zsh
      with_items:
        - root
        - jsumners

    - name: Update rc.local
      template:
        src: templates/rc.local
        dest: /etc/rc.local
        owner: root
        group: root
        mode: '0755'
      notify:
        - restart network

    - include_tasks: tasks/fix-python.yml

    - include_tasks: tasks/sudo.yml
    - include_tasks: tasks/radvd.yml
    - include_tasks: tasks/certs.yml
    - include_tasks: tasks/haproxy.yml
    - include_tasks: tasks/lego.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/dynip.yml
    - include_tasks: tasks/dnsmasq.yml
