- name: Install dnsmasq
  xbps:
    name: dnsmasq

- name: Update dnsmasq config
  template:
    src: templates/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart dnsmasq

- name: Add hosts.d directory
  file:
    dest: /opt/hosts.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Enable dnsmasq
  runit:
    name: dnsmasq
    enabled: yes
