- name: Install dnsmasq
  xbps:
    name: dnsmasq

- name: Update dnsmasq config
  template:
    src: templates/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart dnsmasq

- name: Add hosts.d directory
  file:
    dest: /opt/hosts.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add udm-pro-api-client
  unarchive:
    remote_src: yes
    src: https://github.com/jsumners/udm-pro-api-client/releases/download/v0.1.0/udm-pro-api-client_0.1.0_Linux_x86_64.tar.gz
    dest: /usr/local/bin

- name: Add udm-pro-api-client config
  template:
    src: templates/udm-pro-api-client.yaml
    dest: /etc/udm-pro-api-client.yaml
    owner: root
    group: root
    mode: '0640'

- name: Add get-network-hosts
  template:
    src: templates/get-network-hosts.sh
    dest: /usr/local/bin/get-network-hosts
    owner: root
    group: root
    mode: '0750'

- name: Add udm-pro-api-client cronjob
  cron:
    name: "get network hosts"
    job: "/usr/local/bin/get-network-hosts"
    user: root
    minute: '*/5'

- name: Enable dnsmasq
  runit:
    name: dnsmasq
    enabled: yes
